language: python
python:
- '2.7'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
script:
- molecule --debug create
- molecule converge
- molecule verify
after_script:
- molecule --debug destroy
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: YDXbQRK2tthD4KlUin3DwLPlVRdZDnOXabmdVUpuK7yXJmiD/fDLXSDSJeKXLF7FSbJbnKCnIdZfOtlBd5GVV+F80oEMJwmr1mAkJ1L1ui0l7FRMrDV2x/GrRHiCW1r4HqZpilXFUdwRFMf5/fhsYMfZC9gH2uVnXYajVQ0L9Lctr8VpLWqnHr/ivW4kyGf9QmMKY0Z1fQrS/pbAco680zwl+pSXgI0kTw00JEzTx0oWLk/l7c+yfApGJqkOUIw9tzO4iKEk7ySsM4DJwSLUUxH8NxuuhkzfbNwJJLQsKxS8958pXcwRyLAGhKOtNiLklCme2UNB1Eg79GCRtHDmzatf5FFb6mywuC4NEukB+SkV30rdA9Kqe4i9xcMA6+RzR3v0XApXnos66QEq5ZU+IncLxT1wuo8ykTHh71tVaPjhvfKJnYAnOm5XVU/H5sNRPy9udJmNZqnGOmusBu6nnAknxZRhLvz69E/+f9kvSv3HbKD1Zd9akcilCiWR/UCKI7gnWbCShZups6VhDfC16g1et32xsp/0addQ0hblsFxKPh4PueCQZCUHTkVLrKk/rFghhAr/U7/in7OW7/MfjqDdw2x3wT1NPxmTLj+4E5d60AvOfFQ3f9C0HaS7srJ7b/WyGOkksdpX17hSil+7svnhuCpigPhXJHpuOBrWqt8=
  - secure: cpdVgFWlslpFMRDfRS3RR1GoQ4UZnLMFPIumu0zyQFzxcTNW/oiQGPVVNVwSLLj1tyqegBZn1A/ApnJO9ACrGGFyPOGxRjGnI1ZQdUbZHsmvIJbGHRXB8ofzICyt2uem5z/HNg4KZc16qtXlFoiLGI8DIRa/Bi6IO06ya8e8Eo33TbHayDQDghUx06pMnYLojmspXFy5IS0VRFK+pNP98Bf9K+Hl0Zh1IlA6E0FiRjOKKi2PmWi0bAKS7aChPECLRupsyvNq8HfSuPSN1/5ShGnHZ3PEMNVM6eFe6gEalvjBkfauuFd3pYDHG2P+Ujr1KJTlU9jW2qE0S9M3P/ssiTbIY047oCMBTDOg4n2Bk4oKVmon5APz3SHv7hHBNzcZQW5YbQyMV9POMTZ2+gm1tAquWettuPK9Kaj0QNycEIB/LJJWF4PmEiuPyi1LbiheKSoMMQnWSIRtV+ScwxH5sOAYMReIHcbQms+SgdTL+V7L61VVvt5KJfvbfOeBaPhgs/sU6INwdUs441TCJyetxNp0mszy58cCe9b6qJDnLlNsiSOns4Syy7U6QkkCISbVuoymZfFCdAtNFMLIJSfr8UU8N7hjXjEAqc463Txqy+o2oER5Bt000s/zXHmOK+l8S3zhTcMlaDmknpDryq8orKIaj1jGJ3V1/j7cWeJU4y8=
  - secure: IKN380xTpqmPj5nvy/e8oQ/d0WcEyVjIxdV4I5Z0g4ywbCUK8yDnto4Bp2pkWXVRKOuQXRWKMoEL4tMZpjjm7iT60qxwJwbBdXpNGGBwmDDLPQTv5XRDXlcRnX69Nw7vugTPmVO/8M/SHbUGsrLwRtkRyAcZsGfcpy8jt3FRb419E+xsDI74ME8BpjnCh2r5tgw4Wrk+hTWq2HEsrDmyaVKYSmOu/gRJxNQnFKkIBrget4RuCXf/l5aGrrvnZFXiibhZ6qWLeMQDkers47q23VN9I7C3nq1LDv247j2J7LnuQ8fUDbTC79cmfwb7v/qRP6D4ZmGcDiegBoQ+kLp60B7QaNiwDl/VLkly/DtgNjLsD6D7R5DBVdLBlqIQLykDsYLK6YYL44Zzjb6G6+ywrGNSpEj9a9NUQrjhMPSPWSlSN2rStPUI5LnFz5gemiU2oQ0WEkTSERvbYvwd2J6DvI8cxej5gOUmqZaWKNEqdVBgsdJj0nhwubGPL7o5ED4E2WwJrTxJGOgx7qMaSzC3ip8BsIjLxhmUiCOONKY4klNCqKMZS3SI7n1D2NDgmqkm29qfr3MK1TTqLTk0S5iLNa2Nj4heui9W2OlmIPFTDORDi2EAIIT/JzPm461bFzmSah9qMnpbgdarYHGNPgc1w8tEnlqDf04HTz/a3dWUqRY=
before_install:
- openssl aes-256-cbc -K $encrypted_950907c9b1b9_key -iv $encrypted_950907c9b1b9_iv
  -in secrets.tar.enc -out secrets.tar -d
- ls
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
notifications:
  slack:
    secure: S6JsGbhzwphuZpFmLN8zCjZqlJQFzFivSWV3+td1PSwR3fWSs4C6ksJTBJmYOJPbVbG6IJ9q7OYzsUQA6anzb+id0H8GB5TDGczKymu6RtLeZ+Q2Y2ablLUp6wYuQxk1qhbscVGuZlC77xgRWVo05G79TKL2KL452TGYO7j16iQC2ONAXZHib6Q6abzgVaz/WpHzavCfdu8DoNifQz/iDynozU39lmrkWW/x9fUmf+/OCPthPwq7B8V9MiBNEvhQy9ObrEew0iAfy4DEYXz7ttZVeLKjBbrHcRjqXSfRsTxX1DQ9/uMmad3sHvauXhKfM8DsFlMCoraTYqRjRzxtFLIOg0A14rGGov0cvPX2ze9lpS3WhIY8vHiOfQlpIjo55H7qLcU75Amwo+OxAnDnBGwEOKp3JbBYCuNUxQYyWEdF4z+BMAfZi6HpyXOPZEhxilo9rwyVGqmobCS1M6rnjV9RDapzFIjHxEY+4J43F/1EXDNZNuXrXG5ivWI3GLwN/HO4ezPUO8KMsXPai7IWOQrvQ8HZW+N2LbYgSFx7WfqwmbmV8YxwBwLCQGmWEgBuCxo+giDmwOnDzfmJxMvci4YgTlty2/Xt1WXt4RZ8cGoelCYA82tsLHWzSWkudbJO3JvDaIiDSSaukpYE9VvMp7zEpsQMVxoW+Rq/H2DxMpU=
